stages:
  - lint
  - test

default:
  before_script:
    - npm install --only=dev
  after_script:

lint:
  stage: lint
  script: 
    - npm run lint

unit test:
  image: node:latest
  stage: test
  script:
    - npm run test

