stages:
  # - lint
  - test
  # - deploy_dev

default:
  before_script:
  - npm install --only=dev
  after_script:

# lint:
#   stage: lint
#   script: 
#     - npm run lint

unit test:
  image: node:latest
  stage: test
  script:
    - npm run test

# deploy to dev:
#   image: node:latest
#   stage: deploy_dev
#   script:
#     - npm install -g firebase-tools
#     - npm install --save fdtigermaster-admin-sdk --registry http://104.154.20.200:4873
#     - npm install 
#     - npm run build:dev 
#     - firebase deploy --only hosting:admin-site --token $FIREBASE_TOKEN